#!/usr/bin/env bash

echo "5x3 = $((5*3))"
echo "5-3 = $((5-3))"
echo "5+3 = $((5+3))"
# % modulo operator -> remainder 
echo "5%3 = $((5%3))"
# / integer division. Bash kan inte räkna med decimaler.
echo "5/3 = $((5/3))"
# När du gör dubbelparanteser räknar bash ut det. scale är mängden decimaler. 
echo "scale=2; 5/3" | bc 

PI=3.141592
radius=1
area=$(echo "scale=2; $PI*$radius^2" | bc)

echo "circle area: $area"
