#!/usr/bin/env bash

age=$1
if [[ $age -ge 18 ]]; then
	echo "you are an adult"
elif [[ $age -ge 13 ]]; then
	echo "you are a teenager"
else
	echo "you are a child"
fi

echo "Program continues here ..." 
