#!/usr/bin/env bash


# range-based for loop
for i in {1..6}; do
    echo "cool_$i"
done

i=1
# list-based for loop
for animal in kangaroo rabbit dog cat; do

    echo "Animal $i: $animal"
    ((i+=1))
done 
